version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trivia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  fastapi-service:
    image: fastapi-service:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
